name: build-book

# Only run this when the main branch changes
on:
  push:
    branches:
    - main
    - 'jupyterbook/**'

  pull_request:
    branches:
    - main

# This job installs dependencies and builds the jupyterbook
jobs:
  check-jupyterbook-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Install dependencies
    - name: Set up Python 3.10.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.12

    - name: Install dependencies
      run: |
        cd examples
        python -m pip install --upgrade pip wheel
        python -m pip install -r example_requirements.txt
        python -m pip install jupyter-book

    # Build the book ensuring that the build treats warnings as errors (-W flag)
    # CLI Reference: https://jupyterbook.org/en/stable/reference/cli.html
    - name: Build the book
      run: |
        cd examples
        jupyter-book build -W .

    # Only the build is tested on CI in the pytket repository. The built pages are deployed from the tket-site repository.
